#!/bin/bash
#####################################
# Alexandra Jansen van Rensburg
# Last modified 23/10/2018 15:27:00
####################################

# Script to summarise variant calls in bcf files as generated by 03a_variant_calling_bluecp3.sh
# outputs a raw combined variant file (.bcf) and a filtered file (.bcf) in the input folder. 
# Runs in a few minutes in the home directory (don't need to submit to Blue Crystal). 


##Specify resources
#PBS -N 03b_G1.Allbatches  ##job name
#PBS -l nodes=1:ppn=1  #nr of nodes and processors per node
#PBS -l mem=16gb #RAM
#PBS -l walltime=10:00:00 ##wall time.  
#PBS -j oe  #concatenates error and output files (with prefix job1)

##Load modules
module load apps/bcftools-1.8

##Define variables
SPECIES="G1"

##Work in current directory
cd $PBS_O_WORKDIR 

bcftools concat -O b -a -d none -f 03_variants/bcflist.ALL --threads 1  > 03_variants.FINALTESTS/$SPECIES.raw.bcf
bcftools filter -S . -O u -e 'FMT/DP=0' $SPECIES.raw.bcf | bcftools view -O b -o $SPECIES.raw.bcf
bcftools index 03_variants/$SPECIES.raw.bcf
